language: python

services:
  - postgresql

python:
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"

env:
  - DJANGO="django==1.8.2"

branches:
  only:
    - master

# command to install requirements
install:
  - pip install $DJANGO
  - pip install -r requirements-test.txt
  - python setup.py -q develop

before_script:
  - createdb django_rest_tools_tests
  - psql -U postgres -d django_rest_tools_tests -c "CREATE EXTENSION postgis;"
  - psql -U postgres -d django_rest_tools_tests -c "CREATE EXTENSION postgis_topology;"

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source=django_rest_tools runtests.py

after_success:
  coveralls
